### PR TITLE
Allow Multijob registration

### PR DESCRIPTION
**Pull request by BurntJannings**
Allow multiple jobs to be alerted from one alert

### CODE REVIEW

**Review by DavFount — APPROVED** [review]

**Comment by Quiteck1983** [comment]
I had try this change, but in usuage with bcc-robbery this error will receive
`
[    c-scripting-core] Creating script environments for bcc-robbery
[script:bcc-job-alert] SCRIPT ERROR: @bcc-job-alerts/server/api.lua:5: attempt to call a nil value (global 'RegisterAlert')
[script:bcc-job-alert] > ref (@bcc-job-alerts/server/api.lua:5)
[script:bcc-job-alert] > fn (@bcc-robbery/server/server.lua:14)
[  script:bcc-robbery] SCRIPT ERROR: @bcc-robbery/server/server.lua:14: 
[  script:bcc-robbery]  An error occurred while calling export `RegisterAlert` in resource `bcc-job-alerts`:
[  script:bcc-robbery]   nil
[  script:bcc-robbery]  ---
[           resources] Started resource bcc-robbery
`

**Comment by iseeyoucopy** [comment]
I think you need to ensure the bcc-job-alerts before bcc-robbery

example in server.cfg it should be like this

 `ensure bcc-job-alerts`
  `ensure bcc-robbery`

**Comment by Quiteck1983** [comment]
> I think you need to ensure the bcc-job-alerts before bcc-robbery
> 
> example in server.cfg it should be like this
> 
> `ensure bcc-job-alerts` `ensure bcc-robbery`

That's how I have it.
Before the change, bcc-robbery successfully triggered the job alert

**Comment by BurntJannings** [comment]
Have you changed your BCC robbery table layout to match the new layout in job alerts? ie the jobs and jobgrade tables??

**Comment by Quiteck1983** [comment]
yes, i did.
But when I copy these files, i think there is an error in server/main.lua  in function RegisterAlert at line 40.
There is an "end" missing. I have closed at line 52 and restart without errors.

**Comment by BurntJannings** [comment]
I see that now, missing end, it has been updated

**Pull request merged**
